FROM python:3.12-slim

WORKDIR /app

COPY ../requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

COPY .. /app

RUN pip install -e /app

EXPOSE 7860

WORKDIR /app/server
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "7860"]
